"""Python-native diagram models compiled to editable PowerPoint shapes."""

from .compiler import (
    BackendName,
    Bounds,
    ColorMapName,
    ColorMapOptions,
    CompileBackend,
    CompileResult,
    DiagramCompiler,
    PlacementPreset,
    RelativeBounds,
    SceneResult,
    StylePreset,
    build_scene,
    compile_diagram,
    render_mermaid,
    resolve_diagram_bounds,
)
from .diagnostics import (
    Diagnostic,
    DiagramPptxError,
    ImageExportDependencyError,
    MermaidParseError,
    MermaidRuntimeError,
    PartialModelMutationError,
)
from .export import ExportResult, ImageFormat, save_diagram, to_jpeg, to_png, to_svg
from .layout.layered import LayeredLayout
from .mermaid import parse_mermaid, serialize_mermaid
from .mermaid_registry import (
    MERMAID_COMPATIBILITY_VERSION,
    MERMAID_NATIVE_KINDS,
    MERMAID_SYNTAX_FAMILIES,
    MermaidSyntaxFamily,
    mermaid_support_rows,
)
from .model import (
    ClassDiagram,
    ClassNode,
    ClassRelationship,
    Diagram,
    DiagramEdge,
    DiagramError,
    DiagramGroup,
    DiagramNode,
    EntityRelationshipDiagram,
    ERAttribute,
    EREntity,
    ERRelationship,
    FlowDiagram,
    FlowEdge,
    FlowGroup,
    FlowNode,
    MermaidDocument,
    MermaidSourceDiagram,
    NodeShape,
    SequenceDiagram,
    SequenceEvent,
    SequenceParticipant,
    StateDiagram,
    StateNode,
    StateTransition,
    diagram_from_dict,
)
from .render.python_pptx import PythonPptxRenderer, RenderResult, RenderTheme
from .render.svg import SvgRenderer, SvgRenderResult
from .scene import (
    Box,
    DrawingScene,
    Point,
    SceneConnector,
    SceneContainer,
    SceneShape,
    SceneText,
)
from .styles import (
    ColorMapStyle,
    DiagramTheme,
    ElementStyle,
    StyleResolver,
    contrast_text_color,
    sample_colormap,
)
from .typography import DiagramSettings, FontFit, FontSize, TypographySettings

__all__ = [
    "Box",
    "BackendName",
    "Bounds",
    "ClassDiagram",
    "ClassNode",
    "ClassRelationship",
    "CompileBackend",
    "CompileResult",
    "ColorMapName",
    "ColorMapOptions",
    "ColorMapStyle",
    "Diagnostic",
    "Diagram",
    "DiagramCompiler",
    "DiagramEdge",
    "DiagramError",
    "DiagramGroup",
    "DiagramNode",
    "DiagramPptxError",
    "DiagramSettings",
    "DiagramTheme",
    "DrawingScene",
    "ERAttribute",
    "EREntity",
    "ERRelationship",
    "ElementStyle",
    "EntityRelationshipDiagram",
    "FlowDiagram",
    "FlowEdge",
    "FlowGroup",
    "FlowNode",
    "FontFit",
    "FontSize",
    "ExportResult",
    "ImageExportDependencyError",
    "ImageFormat",
    "LayeredLayout",
    "MermaidDocument",
    "MermaidSourceDiagram",
    "MermaidSyntaxFamily",
    "MERMAID_COMPATIBILITY_VERSION",
    "MERMAID_NATIVE_KINDS",
    "MERMAID_SYNTAX_FAMILIES",
    "MermaidParseError",
    "MermaidRuntimeError",
    "NodeShape",
    "PartialModelMutationError",
    "PlacementPreset",
    "Point",
    "PythonPptxRenderer",
    "RenderResult",
    "RenderTheme",
    "RelativeBounds",
    "SceneResult",
    "SceneConnector",
    "SceneContainer",
    "SceneShape",
    "SceneText",
    "SequenceDiagram",
    "SequenceEvent",
    "SequenceParticipant",
    "StateDiagram",
    "StateNode",
    "StateTransition",
    "StyleResolver",
    "StylePreset",
    "SvgRenderResult",
    "SvgRenderer",
    "TypographySettings",
    "build_scene",
    "compile_diagram",
    "contrast_text_color",
    "diagram_from_dict",
    "parse_mermaid",
    "mermaid_support_rows",
    "render_mermaid",
    "resolve_diagram_bounds",
    "sample_colormap",
    "serialize_mermaid",
    "save_diagram",
    "to_jpeg",
    "to_png",
    "to_svg",
]

__version__ = "0.1.0b2"
