architecture-beta
    group cloud(cloud)[Cloud]
    service api(server)[API] in cloud
    service worker(server)[Worker] in cloud
    service db(database)[Database] in cloud
    api:R --> L:worker
    worker:B --> T:db
